export default {
  CREATED: "Created successfully.",
  SUCCESSFULL: "Successfully loaded",
  LOGIN_SUCCESS: "Login successful",
  UPDATED: "Updated successfully.",
  DELETED: "Deleted successfully.",
  ALREADY_EXIST: "Already Exist",
  LOGIN_FAILED: "Login failed",
  NOT_AUTHORIZED: "Not authorized.",
  NOT_FOUND: "Data not found.",
  DOES_NOT_EXIST: "Does not exist.",
  INVALID_DATA: "Invalid data",
  BAD_REQUEST: "Bad Request.",
  UNABALE_TO_PROCESS_REQUEST: "Unable to process your request.",
  DB_WRITE_FAILED: "Something went wrong!",
  UNKNOWN_ERROR: "Something went wrong. Please try again.",
};
