export default {
  statusTypes: ["active", "deleted"],
  articleTypes: ["news", "analysis", "opinion"],
  approvalStatusTypes: ["pending", "approved", "rejected", "duplicate"],
  feedSourceTypes: ["ani", "reuters", "custom"],
  articleFilterTypes: ["featured", "popular", "archive", "recent"],
  imageTypes: ["jpeg", "png", "WebP", "tiff", "jpg"],
  sortByKeys: [
    "createdAt",
    "-createdAt",
    "updatedAt",
    "-updatedAt",
    "_id",
    "-_id",
  ],
  minShortStr: 1,
  maxShortStr: 100,
  minStr: 1,
  maxStr: 200,
  minLongStr: 1,
  maxLongStr: 1000,
  minVeryLongStr: 1,
  maxVeryLongStr: 10000,
};
